version: '3'
services:
  yolov8_fastapi:
    build: .
    restart: "always"
    volumes:
    - ./:/app
    working_dir: /app
    # ports:
    #   - "8001:8001"
    expose:
      - "8000"
    scale: 3 
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
  load_balancer:
    image: nginx:latest
    ports:
      - "8001:8001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - yolov8_fastapi